import type { CharacterStats } from "./classes.js";

export type ArmorSlot =
  | "chest"
  | "legs"
  | "boots"
  | "helm"
  | "shoulders"
  | "gloves"
  | "belt"
  | "ring"
  | "amulet";
export type WeaponSlot = "weapon";
export type EquipmentSlot = ArmorSlot | WeaponSlot;

export interface ItemStatBonuses extends Partial<CharacterStats> {}

export type ItemRarity = "common" | "uncommon" | "rare" | "epic" | "legendary";

export interface ItemDefinition {
  tokenId: bigint;
  name: string;
  description: string;
  copperPrice: number;
  category: "consumable" | "weapon" | "armor" | "material" | "tool";
  equipSlot?: EquipmentSlot;
  armorSlot?: ArmorSlot;
  statBonuses?: ItemStatBonuses;
  maxDurability?: number;
}

/** Derive rarity from copper price. */
export function getItemRarity(copperPrice: number): ItemRarity {
  if (copperPrice >= 600) return "legendary";
  if (copperPrice >= 350) return "epic";
  if (copperPrice >= 150) return "rare";
  if (copperPrice >= 50) return "uncommon";
  return "common";
}

export const ITEM_CATALOG: ItemDefinition[] = [
  // --- Consumables ---
  {
    tokenId: 0n,
    name: "Health Potion",
    description: "Restores 50 HP instantly.",
    copperPrice: 10,
    category: "consumable",
  },
  {
    tokenId: 1n,
    name: "Raw Meat",
    description: "Uncooked meat from slain beasts. Can be cooked for better nutrition.",
    copperPrice: 3,
    category: "material",
  },
  // --- Weapons ---
  {
    tokenId: 2n,
    name: "Iron Sword",
    description: "A sturdy blade forged from iron. +8 ATK.",
    copperPrice: 100,
    category: "weapon",
    equipSlot: "weapon",
    statBonuses: { str: 8 },
    maxDurability: 60,
  },
  {
    tokenId: 3n,
    name: "Steel Longsword",
    description: "A well-balanced longsword of tempered steel. +14 ATK.",
    copperPrice: 250,
    category: "weapon",
    equipSlot: "weapon",
    statBonuses: { str: 14 },
    maxDurability: 80,
  },
  {
    tokenId: 4n,
    name: "Hunter's Bow",
    description: "A lightweight bow favored by meadow hunters. +10 ATK.",
    copperPrice: 150,
    category: "weapon",
    equipSlot: "weapon",
    statBonuses: { str: 4, agi: 6 },
    maxDurability: 70,
  },
  {
    tokenId: 5n,
    name: "Battle Axe",
    description: "A heavy axe that cleaves through armor. +18 ATK.",
    copperPrice: 400,
    category: "weapon",
    equipSlot: "weapon",
    statBonuses: { str: 18, agi: -1 },
    maxDurability: 95,
  },
  {
    tokenId: 6n,
    name: "Apprentice Staff",
    description: "A gnarled staff crackling with faint energy. +12 MAG.",
    copperPrice: 200,
    category: "weapon",
    equipSlot: "weapon",
    statBonuses: { int: 12, faith: 3 },
    maxDurability: 65,
  },
  // --- Armor ---
  {
    tokenId: 7n,
    name: "Oak Shield",
    description: "A solid shield carved from oak wood. +6 DEF.",
    copperPrice: 80,
    category: "armor",
    equipSlot: "weapon",
    statBonuses: { def: 6 },
    maxDurability: 85,
  },
  {
    tokenId: 8n,
    name: "Leather Vest",
    description: "Light armor stitched from tanned hides. +4 DEF.",
    copperPrice: 60,
    category: "armor",
    equipSlot: "chest",
    armorSlot: "chest",
    statBonuses: { def: 4, hp: 4 },
    maxDurability: 70,
  },
  {
    tokenId: 9n,
    name: "Chainmail Shirt",
    description: "Interlocking iron rings provide solid protection. +10 DEF.",
    copperPrice: 300,
    category: "armor",
    equipSlot: "chest",
    armorSlot: "chest",
    statBonuses: { def: 10, hp: 12 },
    maxDurability: 100,
  },
  {
    tokenId: 10n,
    name: "Iron Helm",
    description: "A simple helm that guards against headshots. +3 DEF.",
    copperPrice: 45,
    category: "armor",
    equipSlot: "helm",
    armorSlot: "helm",
    statBonuses: { def: 3, hp: 3 },
    maxDurability: 55,
  },
  {
    tokenId: 12n,
    name: "Leather Leggings",
    description: "Flexible leggings. +2 DEF, +1 AGI.",
    copperPrice: 55,
    category: "armor",
    equipSlot: "legs",
    armorSlot: "legs",
    statBonuses: { def: 2, agi: 1 },
    maxDurability: 60,
  },
  {
    tokenId: 13n,
    name: "Traveler Boots",
    description: "Sturdy boots for long marches. +1 DEF, +2 AGI.",
    copperPrice: 50,
    category: "armor",
    equipSlot: "boots",
    armorSlot: "boots",
    statBonuses: { def: 1, agi: 2 },
    maxDurability: 58,
  },
  {
    tokenId: 14n,
    name: "Bronze Shoulders",
    description: "Simple shoulder guards. +3 DEF.",
    copperPrice: 70,
    category: "armor",
    equipSlot: "shoulders",
    armorSlot: "shoulders",
    statBonuses: { def: 3 },
    maxDurability: 75,
  },
  {
    tokenId: 15n,
    name: "Padded Gloves",
    description: "Reinforced gloves. +1 STR, +1 DEF.",
    copperPrice: 40,
    category: "armor",
    equipSlot: "gloves",
    armorSlot: "gloves",
    statBonuses: { str: 1, def: 1 },
    maxDurability: 50,
  },
  {
    tokenId: 16n,
    name: "Guard Belt",
    description: "A belt that stabilizes your stance. +2 DEF, +4 HP.",
    copperPrice: 60,
    category: "armor",
    equipSlot: "belt",
    armorSlot: "belt",
    statBonuses: { def: 2, hp: 4 },
    maxDurability: 65,
  },
  {
    tokenId: 17n,
    name: "Iron Greaves",
    description: "Heavy greaves for frontline fighters. +5 DEF.",
    copperPrice: 130,
    category: "armor",
    equipSlot: "legs",
    armorSlot: "legs",
    statBonuses: { def: 5, hp: 6 },
    maxDurability: 90,
  },
  {
    tokenId: 18n,
    name: "Steel Sabatons",
    description: "Armored boots. +3 DEF, +1 AGI.",
    copperPrice: 110,
    category: "armor",
    equipSlot: "boots",
    armorSlot: "boots",
    statBonuses: { def: 3, agi: 1 },
    maxDurability: 85,
  },
  {
    tokenId: 19n,
    name: "Knight Gauntlets",
    description: "Heavy gauntlets. +2 STR, +3 DEF.",
    copperPrice: 150,
    category: "armor",
    equipSlot: "gloves",
    armorSlot: "gloves",
    statBonuses: { str: 2, def: 3 },
    maxDurability: 88,
  },
  {
    tokenId: 20n,
    name: "War Belt",
    description: "Battle-forged belt. +4 DEF, +8 HP.",
    copperPrice: 140,
    category: "armor",
    equipSlot: "belt",
    armorSlot: "belt",
    statBonuses: { def: 4, hp: 8 },
    maxDurability: 92,
  },
  {
    tokenId: 21n,
    name: "Steel Pauldrons",
    description: "Reinforced pauldrons. +5 DEF.",
    copperPrice: 165,
    category: "armor",
    equipSlot: "shoulders",
    armorSlot: "shoulders",
    statBonuses: { def: 5, hp: 4 },
    maxDurability: 95,
  },
  // --- Materials ---
  {
    tokenId: 11n,
    name: "Wolf Pelt",
    description: "A pelt harvested from a slain wolf.",
    copperPrice: 5,
    category: "material",
  },
  // --- Ores (Materials) ---
  {
    tokenId: 22n,
    name: "Coal Ore",
    description: "Common black ore used for basic smelting.",
    copperPrice: 8,
    category: "material",
  },
  {
    tokenId: 23n,
    name: "Tin Ore",
    description: "Lightweight ore with a silvery sheen.",
    copperPrice: 12,
    category: "material",
  },
  {
    tokenId: 24n,
    name: "Copper Ore",
    description: "Reddish-brown ore prized by blacksmiths.",
    copperPrice: 20,
    category: "material",
  },
  {
    tokenId: 25n,
    name: "Silver Ore",
    description: "Rare ore that gleams in the light.",
    copperPrice: 45,
    category: "material",
  },
  {
    tokenId: 26n,
    name: "Gold Ore",
    description: "Extremely rare precious ore.",
    copperPrice: 100,
    category: "material",
  },
  // --- Pickaxes (Tools) ---
  {
    tokenId: 27n,
    name: "Stone Pickaxe",
    description: "Crude pickaxe for mining common ores. Tier 1.",
    copperPrice: 30,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 40,
  },
  {
    tokenId: 28n,
    name: "Iron Pickaxe",
    description: "Sturdy pickaxe for harder ores. Tier 2.",
    copperPrice: 80,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 60,
  },
  {
    tokenId: 29n,
    name: "Steel Pickaxe",
    description: "Refined pickaxe for rare ores. Tier 3.",
    copperPrice: 200,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 80,
  },
  {
    tokenId: 30n,
    name: "Mithril Pickaxe",
    description: "Legendary pickaxe that mines gold veins. Tier 4.",
    copperPrice: 500,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 100,
  },
  // --- Flowers (Materials) ---
  {
    tokenId: 31n,
    name: "Meadow Lily",
    description: "Delicate white flowers found in sunny meadows.",
    copperPrice: 5,
    category: "material",
  },
  {
    tokenId: 32n,
    name: "Wild Rose",
    description: "Fragrant pink roses with thorny stems.",
    copperPrice: 6,
    category: "material",
  },
  {
    tokenId: 33n,
    name: "Dandelion",
    description: "Common yellow flower with medicinal properties.",
    copperPrice: 3,
    category: "material",
  },
  {
    tokenId: 34n,
    name: "Clover",
    description: "Lucky four-leaf clover, rare and valuable.",
    copperPrice: 4,
    category: "material",
  },
  {
    tokenId: 35n,
    name: "Lavender",
    description: "Purple aromatic herb with calming properties.",
    copperPrice: 15,
    category: "material",
  },
  {
    tokenId: 36n,
    name: "Sage",
    description: "Silvery-green herb used in magical rituals.",
    copperPrice: 18,
    category: "material",
  },
  {
    tokenId: 37n,
    name: "Mint",
    description: "Refreshing herb with a cool, crisp scent.",
    copperPrice: 12,
    category: "material",
  },
  {
    tokenId: 38n,
    name: "Moonflower",
    description: "Rare white bloom that only opens at night.",
    copperPrice: 40,
    category: "material",
  },
  {
    tokenId: 39n,
    name: "Starbloom",
    description: "Ethereal flower that glows with starlight.",
    copperPrice: 55,
    category: "material",
  },
  {
    tokenId: 40n,
    name: "Dragon's Breath",
    description: "Legendary crimson flower imbued with draconic energy.",
    copperPrice: 120,
    category: "material",
  },
  // --- Sickles (Herbalism Tools) ---
  {
    tokenId: 41n,
    name: "Basic Sickle",
    description: "Simple curved blade for gathering common herbs. Tier 1.",
    copperPrice: 25,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 35,
  },
  {
    tokenId: 42n,
    name: "Iron Sickle",
    description: "Sturdy iron blade for cutting tougher plants. Tier 2.",
    copperPrice: 70,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 55,
  },
  {
    tokenId: 43n,
    name: "Steel Sickle",
    description: "Razor-sharp steel blade for rare flowers. Tier 3.",
    copperPrice: 180,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 75,
  },
  {
    tokenId: 44n,
    name: "Enchanted Sickle",
    description: "Magical sickle that harvests legendary blooms. Tier 4.",
    copperPrice: 450,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 95,
  },
  // --- Potions (Alchemy Products) ---
  {
    tokenId: 45n,
    name: "Minor Health Potion",
    description: "Restores 30 HP. Brewed from meadow lilies and dandelion.",
    copperPrice: 15,
    category: "consumable",
  },
  {
    tokenId: 46n,
    name: "Minor Mana Potion",
    description: "Restores 20 MP. Brewed from wild roses and clover.",
    copperPrice: 18,
    category: "consumable",
  },
  {
    tokenId: 47n,
    name: "Stamina Elixir",
    description: "Increases stamina regeneration for 5 minutes.",
    copperPrice: 30,
    category: "consumable",
  },
  {
    tokenId: 48n,
    name: "Wisdom Potion",
    description: "Grants +10 INT for 10 minutes. Infused with sage and moonflower.",
    copperPrice: 50,
    category: "consumable",
  },
  {
    tokenId: 49n,
    name: "Swift Step Potion",
    description: "Increases movement speed by 20% for 5 minutes.",
    copperPrice: 25,
    category: "consumable",
  },
  {
    tokenId: 50n,
    name: "Greater Health Potion",
    description: "Restores 100 HP. Potent healing brew.",
    copperPrice: 80,
    category: "consumable",
  },
  {
    tokenId: 51n,
    name: "Greater Mana Potion",
    description: "Restores 70 MP. Distilled from starbloom essence.",
    copperPrice: 95,
    category: "consumable",
  },
  {
    tokenId: 52n,
    name: "Elixir of Strength",
    description: "Grants +15 STR for 15 minutes. Dragon's breath infusion.",
    copperPrice: 150,
    category: "consumable",
  },
  {
    tokenId: 53n,
    name: "Elixir of Vitality",
    description: "Grants +20 HP and +10 DEF for 15 minutes.",
    copperPrice: 180,
    category: "consumable",
  },
  {
    tokenId: 54n,
    name: "Philosopher's Elixir",
    description: "Legendary brew that grants +20 to all stats for 30 minutes.",
    copperPrice: 400,
    category: "consumable",
  },
  // --- Enchantment Elixirs (Alchemy Products) ---
  {
    tokenId: 55n,
    name: "Fire Enchantment Elixir",
    description: "Imbues weapons with eternal flames. +5 STR, +10% fire damage.",
    copperPrice: 150,
    category: "consumable",
  },
  {
    tokenId: 56n,
    name: "Ice Enchantment Elixir",
    description: "Sheathes weapons in frost. +3 STR, +2 AGI, 20% slow chance.",
    copperPrice: 140,
    category: "consumable",
  },
  {
    tokenId: 57n,
    name: "Lightning Enchantment Elixir",
    description: "Electrifies weapons. +4 STR, +3 AGI, 30% chain lightning.",
    copperPrice: 160,
    category: "consumable",
  },
  {
    tokenId: 58n,
    name: "Holy Enchantment Elixir",
    description: "Blesses weapons with divine light. +4 STR, +2 DEF, heals 5 HP on hit.",
    copperPrice: 180,
    category: "consumable",
  },
  {
    tokenId: 59n,
    name: "Shadow Enchantment Elixir",
    description: "Cloaks weapons in darkness. +6 STR, +1 AGI, +15% crit chance.",
    copperPrice: 170,
    category: "consumable",
  },
  {
    tokenId: 60n,
    name: "Sharpness Elixir",
    description: "Hones weapons to impossible keenness. +8 STR, +20% vs armor.",
    copperPrice: 200,
    category: "consumable",
  },
  {
    tokenId: 61n,
    name: "Durability Elixir",
    description: "Makes equipment nearly unbreakable. +3 DEF, -50% durability loss.",
    copperPrice: 190,
    category: "consumable",
  },

  // --- Skinning Materials ---
  {
    tokenId: 62n,
    name: "Scrap Leather",
    description: "Rough, low-quality leather from common creatures.",
    copperPrice: 3,
    category: "material",
  },
  {
    tokenId: 63n,
    name: "Light Leather",
    description: "Soft, pliable leather suitable for basic armor.",
    copperPrice: 6,
    category: "material",
  },
  {
    tokenId: 64n,
    name: "Medium Leather",
    description: "Sturdy leather from mid-tier beasts.",
    copperPrice: 12,
    category: "material",
  },
  {
    tokenId: 65n,
    name: "Wolf Pelt",
    description: "Thick fur pelt from a slain wolf.",
    copperPrice: 10,
    category: "material",
  },
  {
    tokenId: 66n,
    name: "Bear Hide",
    description: "Extremely durable hide from a forest bear.",
    copperPrice: 25,
    category: "material",
  },
  {
    tokenId: 67n,
    name: "Spider Silk",
    description: "Fine, enchanted silk harvested from giant spiders.",
    copperPrice: 18,
    category: "material",
  },
  {
    tokenId: 68n,
    name: "Small Bone",
    description: "Common bone fragments from small creatures.",
    copperPrice: 2,
    category: "material",
  },
  {
    tokenId: 69n,
    name: "Thick Bone",
    description: "Large bones from powerful beasts.",
    copperPrice: 8,
    category: "material",
  },
  {
    tokenId: 70n,
    name: "Heavy Leather",
    description: "Premium leather from dangerous creatures.",
    copperPrice: 30,
    category: "material",
  },
  {
    tokenId: 71n,
    name: "Shadow Pelt",
    description: "Mystical fur that shimmers with dark energy.",
    copperPrice: 60,
    category: "material",
  },
  {
    tokenId: 72n,
    name: "Ancient Bone",
    description: "Enchanted bones from undead or ancient beings.",
    copperPrice: 35,
    category: "material",
  },
  {
    tokenId: 73n,
    name: "Troll Hide",
    description: "Regenerative hide from a forest troll.",
    copperPrice: 75,
    category: "material",
  },
  {
    tokenId: 74n,
    name: "Golem Core",
    description: "Magical core extracted from an ancient golem.",
    copperPrice: 100,
    category: "material",
  },
  {
    tokenId: 75n,
    name: "Necromancer's Essence",
    description: "Rare essence of dark magic from a powerful necromancer.",
    copperPrice: 200,
    category: "material",
  },

  // --- Skinning Knives (Tools) ---
  {
    tokenId: 76n,
    name: "Rusty Skinning Knife",
    description: "Crude blade for harvesting basic leather. Tier 1.",
    copperPrice: 25,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 50,
  },
  {
    tokenId: 77n,
    name: "Iron Skinning Knife",
    description: "Sharp knife for skinning mid-tier creatures. Tier 2.",
    copperPrice: 70,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 70,
  },
  {
    tokenId: 78n,
    name: "Steel Skinning Knife",
    description: "Professional skinner's blade for rare hides. Tier 3.",
    copperPrice: 180,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 90,
  },
  {
    tokenId: 79n,
    name: "Master Skinner's Blade",
    description: "Legendary blade that harvests the finest materials. Tier 4.",
    copperPrice: 450,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 120,
  },

  // --- Mana Potion (moved from tokenId 1) ---
  {
    tokenId: 80n,
    name: "Mana Potion",
    description: "Restores 30 essence instantly.",
    copperPrice: 15,
    category: "consumable",
  },

  // --- Cooked Food (Cooking Profession) ---
  {
    tokenId: 81n,
    name: "Cooked Meat",
    description: "Grilled meat that restores 30 HP.",
    copperPrice: 8,
    category: "consumable",
  },
  {
    tokenId: 82n,
    name: "Hearty Stew",
    description: "A filling stew that restores 60 HP.",
    copperPrice: 18,
    category: "consumable",
  },
  {
    tokenId: 83n,
    name: "Roasted Boar",
    description: "Succulent roasted boar that restores 100 HP.",
    copperPrice: 35,
    category: "consumable",
  },
  {
    tokenId: 84n,
    name: "Bear Feast",
    description: "A luxurious feast that restores 150 HP.",
    copperPrice: 60,
    category: "consumable",
  },
  {
    tokenId: 85n,
    name: "Hero's Banquet",
    description: "An epic meal that restores 250 HP and grants +5 STR for 5 minutes.",
    copperPrice: 120,
    category: "consumable",
  },

  // --- Smelted Bars (Materials) ---
  {
    tokenId: 86n,
    name: "Tin Bar",
    description: "Refined tin ingot, lightweight and malleable.",
    copperPrice: 18,
    category: "material",
  },
  {
    tokenId: 87n,
    name: "Copper Bar",
    description: "Solid copper ingot prized by blacksmiths.",
    copperPrice: 30,
    category: "material",
  },
  {
    tokenId: 88n,
    name: "Silver Bar",
    description: "Gleaming silver ingot used in fine crafting.",
    copperPrice: 65,
    category: "material",
  },
  {
    tokenId: 89n,
    name: "Gold Bar",
    description: "Precious gold ingot of exceptional purity.",
    copperPrice: 150,
    category: "material",
  },
  {
    tokenId: 90n,
    name: "Steel Alloy",
    description: "High-grade alloy forged from multiple metals. Used for upgrades.",
    copperPrice: 200,
    category: "material",
  },

  // --- Leather Armor — Basic (Tanned) Set ---
  {
    tokenId: 91n,
    name: "Tanned Leather Vest",
    description: "Supple vest crafted from tanned hides. +5 DEF, +3 AGI.",
    copperPrice: 80,
    category: "armor",
    equipSlot: "chest",
    armorSlot: "chest",
    statBonuses: { def: 5, agi: 3, hp: 5 },
    maxDurability: 55,
  },
  {
    tokenId: 92n,
    name: "Tanned Leather Leggings",
    description: "Flexible leggings for nimble fighters. +3 DEF, +2 AGI.",
    copperPrice: 65,
    category: "armor",
    equipSlot: "legs",
    armorSlot: "legs",
    statBonuses: { def: 3, agi: 2 },
    maxDurability: 50,
  },
  {
    tokenId: 93n,
    name: "Tanned Leather Boots",
    description: "Lightweight boots for swift movement. +2 DEF, +3 AGI.",
    copperPrice: 55,
    category: "armor",
    equipSlot: "boots",
    armorSlot: "boots",
    statBonuses: { def: 2, agi: 3 },
    maxDurability: 50,
  },
  {
    tokenId: 94n,
    name: "Tanned Leather Helm",
    description: "A fitted cap of tanned leather. +3 DEF, +1 AGI.",
    copperPrice: 50,
    category: "armor",
    equipSlot: "helm",
    armorSlot: "helm",
    statBonuses: { def: 3, agi: 1 },
    maxDurability: 50,
  },
  {
    tokenId: 95n,
    name: "Tanned Leather Shoulders",
    description: "Padded shoulder guards. +3 DEF, +1 AGI.",
    copperPrice: 55,
    category: "armor",
    equipSlot: "shoulders",
    armorSlot: "shoulders",
    statBonuses: { def: 3, agi: 1 },
    maxDurability: 50,
  },
  {
    tokenId: 96n,
    name: "Tanned Leather Gloves",
    description: "Thin gloves for dexterous work. +1 DEF, +2 AGI.",
    copperPrice: 45,
    category: "armor",
    equipSlot: "gloves",
    armorSlot: "gloves",
    statBonuses: { def: 1, agi: 2 },
    maxDurability: 50,
  },
  {
    tokenId: 97n,
    name: "Tanned Leather Belt",
    description: "A sturdy belt with pouches. +2 DEF, +3 HP.",
    copperPrice: 45,
    category: "armor",
    equipSlot: "belt",
    armorSlot: "belt",
    statBonuses: { def: 2, hp: 3 },
    maxDurability: 50,
  },

  // --- Leather Armor — Reinforced Set ---
  {
    tokenId: 98n,
    name: "Reinforced Hide Vest",
    description: "Heavy-duty leather vest reinforced with bone plates. +8 DEF, +4 AGI.",
    copperPrice: 160,
    category: "armor",
    equipSlot: "chest",
    armorSlot: "chest",
    statBonuses: { def: 8, agi: 4, hp: 8 },
    maxDurability: 75,
  },
  {
    tokenId: 99n,
    name: "Reinforced Hide Leggings",
    description: "Thick leggings layered with hardened hide. +6 DEF, +3 AGI.",
    copperPrice: 130,
    category: "armor",
    equipSlot: "legs",
    armorSlot: "legs",
    statBonuses: { def: 6, agi: 3, hp: 4 },
    maxDurability: 70,
  },
  {
    tokenId: 100n,
    name: "Reinforced Hide Boots",
    description: "Armored boots with hide padding. +4 DEF, +4 AGI.",
    copperPrice: 110,
    category: "armor",
    equipSlot: "boots",
    armorSlot: "boots",
    statBonuses: { def: 4, agi: 4 },
    maxDurability: 65,
  },
  {
    tokenId: 101n,
    name: "Reinforced Hide Helm",
    description: "A hardened helm with bone ridges. +5 DEF, +2 AGI.",
    copperPrice: 100,
    category: "armor",
    equipSlot: "helm",
    armorSlot: "helm",
    statBonuses: { def: 5, agi: 2, hp: 3 },
    maxDurability: 65,
  },
  {
    tokenId: 102n,
    name: "Reinforced Hide Shoulders",
    description: "Broad shoulder guards of layered hide. +6 DEF, +2 AGI.",
    copperPrice: 120,
    category: "armor",
    equipSlot: "shoulders",
    armorSlot: "shoulders",
    statBonuses: { def: 6, agi: 2 },
    maxDurability: 70,
  },
  {
    tokenId: 103n,
    name: "Reinforced Hide Gloves",
    description: "Thick gauntlets with hide reinforcement. +3 DEF, +3 AGI.",
    copperPrice: 90,
    category: "armor",
    equipSlot: "gloves",
    armorSlot: "gloves",
    statBonuses: { def: 3, agi: 3, str: 1 },
    maxDurability: 65,
  },
  {
    tokenId: 104n,
    name: "Reinforced Hide Belt",
    description: "Wide belt reinforced with bone clasps. +4 DEF, +6 HP.",
    copperPrice: 95,
    category: "armor",
    equipSlot: "belt",
    armorSlot: "belt",
    statBonuses: { def: 4, hp: 6 },
    maxDurability: 70,
  },

  // --- Upgraded Weapons — Reinforced (+25% stats) ---
  {
    tokenId: 105n,
    name: "Reinforced Iron Sword",
    description: "Iron sword reinforced with steel alloy. +10 STR.",
    copperPrice: 180,
    category: "weapon",
    equipSlot: "weapon",
    statBonuses: { str: 10 },
    maxDurability: 75,
  },
  {
    tokenId: 106n,
    name: "Reinforced Steel Longsword",
    description: "Tempered longsword with superior balance. +18 STR.",
    copperPrice: 400,
    category: "weapon",
    equipSlot: "weapon",
    statBonuses: { str: 18 },
    maxDurability: 100,
  },
  {
    tokenId: 107n,
    name: "Reinforced Hunter's Bow",
    description: "Composite bow with metal-tipped limbs. +5 STR, +8 AGI.",
    copperPrice: 250,
    category: "weapon",
    equipSlot: "weapon",
    statBonuses: { str: 5, agi: 8 },
    maxDurability: 88,
  },
  {
    tokenId: 108n,
    name: "Reinforced Battle Axe",
    description: "Heavy axe with a steel alloy head. +23 STR.",
    copperPrice: 600,
    category: "weapon",
    equipSlot: "weapon",
    statBonuses: { str: 23, agi: -1 },
    maxDurability: 119,
  },
  {
    tokenId: 109n,
    name: "Reinforced Apprentice Staff",
    description: "Staff infused with additional arcane energy. +15 INT, +4 FAITH.",
    copperPrice: 350,
    category: "weapon",
    equipSlot: "weapon",
    statBonuses: { int: 15, faith: 4 },
    maxDurability: 81,
  },

  // --- Upgraded Weapons — Masterwork (+50% stats) ---
  {
    tokenId: 110n,
    name: "Masterwork Iron Sword",
    description: "Flawless blade of legendary craftsmanship. +12 STR.",
    copperPrice: 300,
    category: "weapon",
    equipSlot: "weapon",
    statBonuses: { str: 12 },
    maxDurability: 90,
  },
  {
    tokenId: 111n,
    name: "Masterwork Steel Longsword",
    description: "Perfectly balanced longsword. +21 STR.",
    copperPrice: 650,
    category: "weapon",
    equipSlot: "weapon",
    statBonuses: { str: 21 },
    maxDurability: 120,
  },
  {
    tokenId: 112n,
    name: "Masterwork Hunter's Bow",
    description: "A bow of extraordinary precision. +6 STR, +9 AGI.",
    copperPrice: 420,
    category: "weapon",
    equipSlot: "weapon",
    statBonuses: { str: 6, agi: 9 },
    maxDurability: 105,
  },
  {
    tokenId: 113n,
    name: "Masterwork Battle Axe",
    description: "A devastating axe forged by a master smith. +27 STR.",
    copperPrice: 950,
    category: "weapon",
    equipSlot: "weapon",
    statBonuses: { str: 27, agi: -1 },
    maxDurability: 143,
  },
  {
    tokenId: 114n,
    name: "Masterwork Apprentice Staff",
    description: "Staff pulsing with concentrated arcane power. +18 INT, +5 FAITH.",
    copperPrice: 550,
    category: "weapon",
    equipSlot: "weapon",
    statBonuses: { int: 18, faith: 5 },
    maxDurability: 98,
  },

  // --- Disenchanting Scroll (Consumable) ---
  {
    tokenId: 115n,
    name: "Disenchanting Scroll",
    description: "Ancient scroll that strips all enchantments from an equipped item.",
    copperPrice: 100,
    category: "consumable",
  },

  // --- Gems (Materials) ---
  {
    tokenId: 116n,
    name: "Rough Ruby",
    description: "An uncut ruby glimmering with inner fire.",
    copperPrice: 40,
    category: "material",
  },
  {
    tokenId: 117n,
    name: "Rough Sapphire",
    description: "An uncut sapphire radiating cool blue light.",
    copperPrice: 40,
    category: "material",
  },
  {
    tokenId: 118n,
    name: "Rough Emerald",
    description: "An uncut emerald pulsing with natural energy.",
    copperPrice: 40,
    category: "material",
  },
  {
    tokenId: 119n,
    name: "Flawed Diamond",
    description: "A diamond with minor inclusions — still valuable.",
    copperPrice: 80,
    category: "material",
  },
  {
    tokenId: 120n,
    name: "Shadow Opal",
    description: "A dark opal swirling with shadowy energy.",
    copperPrice: 90,
    category: "material",
  },
  {
    tokenId: 121n,
    name: "Arcane Crystal",
    description: "Rare crystal suffused with raw arcane power.",
    copperPrice: 150,
    category: "material",
  },

  // --- Jewelry (Rings & Amulets) ---
  {
    tokenId: 122n,
    name: "Ruby Ring",
    description: "A polished ruby set in gold. +4 STR, +6 HP.",
    copperPrice: 120,
    category: "armor",
    equipSlot: "ring",
    armorSlot: "ring",
    statBonuses: { str: 4, hp: 6 },
    maxDurability: 80,
  },
  {
    tokenId: 123n,
    name: "Sapphire Ring",
    description: "A brilliant sapphire ring. +4 INT, +6 MP.",
    copperPrice: 120,
    category: "armor",
    equipSlot: "ring",
    armorSlot: "ring",
    statBonuses: { int: 4, mp: 6 },
    maxDurability: 80,
  },
  {
    tokenId: 124n,
    name: "Emerald Ring",
    description: "A vibrant emerald ring. +3 AGI, +2 LUCK, +4 HP.",
    copperPrice: 130,
    category: "armor",
    equipSlot: "ring",
    armorSlot: "ring",
    statBonuses: { agi: 3, luck: 2, hp: 4 },
    maxDurability: 80,
  },
  {
    tokenId: 125n,
    name: "Diamond Amulet",
    description: "A radiant diamond pendant. +5 DEF, +8 HP, +3 FAITH.",
    copperPrice: 200,
    category: "armor",
    equipSlot: "amulet",
    armorSlot: "amulet",
    statBonuses: { def: 5, hp: 8, faith: 3 },
    maxDurability: 100,
  },
  {
    tokenId: 126n,
    name: "Shadow Opal Amulet",
    description: "A dark pendant crackling with shadow energy. +4 STR, +3 AGI, +2 LUCK.",
    copperPrice: 220,
    category: "armor",
    equipSlot: "amulet",
    armorSlot: "amulet",
    statBonuses: { str: 4, agi: 3, luck: 2 },
    maxDurability: 100,
  },
  {
    tokenId: 127n,
    name: "Arcane Crystal Amulet",
    description: "A crystalline amulet humming with power. +6 INT, +8 MP, +3 FAITH.",
    copperPrice: 280,
    category: "armor",
    equipSlot: "amulet",
    armorSlot: "amulet",
    statBonuses: { int: 6, mp: 8, faith: 3 },
    maxDurability: 100,
  },
  // --- Gate Reagents (Alchemy outputs for dungeon keys) ---
  {
    tokenId: 128n,
    name: "Crude Gate Essence",
    description: "Unstable essence. Enchant to create E-Key.",
    copperPrice: 30,
    category: "material",
  },
  {
    tokenId: 129n,
    name: "Lesser Gate Essence",
    description: "Refined essence. Enchant to create D-Key.",
    copperPrice: 60,
    category: "material",
  },
  {
    tokenId: 130n,
    name: "Gate Essence",
    description: "Potent reagent. Enchant to create C-Key.",
    copperPrice: 120,
    category: "material",
  },
  {
    tokenId: 131n,
    name: "Greater Gate Essence",
    description: "Powerful reagent. Enchant to create B-Key.",
    copperPrice: 200,
    category: "material",
  },
  {
    tokenId: 132n,
    name: "Superior Gate Essence",
    description: "Superb reagent. Enchant to create A-Key.",
    copperPrice: 350,
    category: "material",
  },
  {
    tokenId: 133n,
    name: "Supreme Gate Essence",
    description: "Legendary reagent. Enchant to create S-Key.",
    copperPrice: 500,
    category: "material",
  },

  // --- Gate Keys (Consumables for opening dungeon gates) ---
  {
    tokenId: 134n,
    name: "E-Key",
    description: "Opens Rank E Dungeon Gates.",
    copperPrice: 50,
    category: "consumable",
  },
  {
    tokenId: 135n,
    name: "D-Key",
    description: "Opens Rank D Dungeon Gates.",
    copperPrice: 100,
    category: "consumable",
  },
  {
    tokenId: 136n,
    name: "C-Key",
    description: "Opens Rank C Dungeon Gates.",
    copperPrice: 200,
    category: "consumable",
  },
  {
    tokenId: 137n,
    name: "B-Key",
    description: "Opens Rank B Dungeon Gates.",
    copperPrice: 350,
    category: "consumable",
  },
  {
    tokenId: 138n,
    name: "A-Key",
    description: "Opens Rank A Dungeon Gates.",
    copperPrice: 600,
    category: "consumable",
  },
  {
    tokenId: 139n,
    name: "S-Key",
    description: "Opens Rank S Dungeon Gates.",
    copperPrice: 1000,
    category: "consumable",
  },

  // --- Tonics (XP Boost Consumables) ---
  {
    tokenId: 140n,
    name: "Meadow Tonic",
    description: "A refreshing tonic brewed from meadow herbs and dew nectar. Grants +50% XP for 5 minutes.",
    copperPrice: 40,
    category: "consumable",
  },
  {
    tokenId: 141n,
    name: "Starbloom Tonic",
    description: "Luminous tonic distilled from starbloom essence. Grants +100% XP for 10 minutes.",
    copperPrice: 120,
    category: "consumable",
  },
  {
    tokenId: 142n,
    name: "Dragon's Breath Tonic",
    description: "Fiery tonic of immense power. Grants +200% XP for 15 minutes. Essential for high-level grinding.",
    copperPrice: 250,
    category: "consumable",
  },
  {
    tokenId: 143n,
    name: "Apprentice's Tonic",
    description: "A sage-infused tonic that sharpens crafting focus. Grants +50% profession XP for 10 minutes.",
    copperPrice: 70,
    category: "consumable",
  },

  // --- Resistance Elixirs ---
  {
    tokenId: 144n,
    name: "Fire Resistance Elixir",
    description: "Grants fire resistance for 15 minutes. Required for volcanic zone mobs.",
    copperPrice: 90,
    category: "consumable",
  },
  {
    tokenId: 145n,
    name: "Shadow Resistance Elixir",
    description: "Grants shadow resistance for 15 minutes. Required for undead zone mobs.",
    copperPrice: 90,
    category: "consumable",
  },
  {
    tokenId: 146n,
    name: "Ice Resistance Elixir",
    description: "Grants ice resistance for 15 minutes. Required for frozen zone mobs.",
    copperPrice: 100,
    category: "consumable",
  },
  {
    tokenId: 147n,
    name: "Lightning Resistance Elixir",
    description: "Grants lightning resistance for 15 minutes. Required for storm zone mobs.",
    copperPrice: 100,
    category: "consumable",
  },
  {
    tokenId: 148n,
    name: "Holy Resistance Elixir",
    description: "Grants holy resistance for 15 minutes. Required for celestial zone mobs.",
    copperPrice: 100,
    category: "consumable",
  },

  // --- Nectars (Gathered Liquids — raw alchemy ingredients) ---
  {
    tokenId: 150n,
    name: "Dew Nectar",
    description: "Morning dew collected from meadow flowers. Common nectar used in basic tonics.",
    copperPrice: 5,
    category: "material",
  },
  {
    tokenId: 151n,
    name: "Suncrest Nectar",
    description: "Golden nectar that pools in sunlit groves. Warm to the touch.",
    copperPrice: 10,
    category: "material",
  },
  {
    tokenId: 152n,
    name: "Moonpetal Nectar",
    description: "Silvery liquid that glows faintly under moonlight. Rare and potent.",
    copperPrice: 20,
    category: "material",
  },
  {
    tokenId: 153n,
    name: "Emberveil Nectar",
    description: "Volcanic nectar with a fiery shimmer. Burns to gather without protection.",
    copperPrice: 30,
    category: "material",
  },
  {
    tokenId: 154n,
    name: "Gloomveil Nectar",
    description: "Dark purple nectar found in shadowed hollows. Absorbs light around it.",
    copperPrice: 25,
    category: "material",
  },
  {
    tokenId: 155n,
    name: "Stormwell Nectar",
    description: "Electrified nectar that crackles with static. Found near lightning-struck ground.",
    copperPrice: 28,
    category: "material",
  },

  // --- Advanced Crafting Materials (Rare reagents for master recipes) ---
  {
    tokenId: 160n,
    name: "Silica Glass",
    description: "Transparent glass forged from pure Silicium at 1,700°C. Stores and transmits magical data.",
    copperPrice: 200,
    category: "material",
  },
  {
    tokenId: 161n,
    name: "Scandix Steel",
    description: "An alloy of Scandix and Ascandium. Absorbs and redirects kinetic energy.",
    copperPrice: 250,
    category: "material",
  },
  {
    tokenId: 162n,
    name: "Cryptonic Crystal",
    description: "Translucent crystal grown under immense pressure. Stores vast magical energy.",
    copperPrice: 350,
    category: "material",
  },
  {
    tokenId: 163n,
    name: "Strontidian Silk",
    description: "Lightweight silk that changes color with the wearer's emotions.",
    copperPrice: 180,
    category: "material",
  },
  {
    tokenId: 164n,
    name: "Zircomium Foam",
    description: "Porous material that absorbs and nullifies sound. Essential for stealth enchantments.",
    copperPrice: 150,
    category: "material",
  },
  {
    tokenId: 165n,
    name: "Molybdium Wire",
    description: "Ultra-thin wire that transmits thoughts and emotions. Used in neural interfaces.",
    copperPrice: 300,
    category: "material",
  },
  {
    tokenId: 166n,
    name: "Ruthemic Glass",
    description: "Glass with unique optical properties. Can bend light, rendering objects invisible.",
    copperPrice: 400,
    category: "material",
  },
  {
    tokenId: 167n,
    name: "Rhodacium Putty",
    description: "Malleable putty that retains any shape indefinitely. Used for enchanted seals.",
    copperPrice: 120,
    category: "material",
  },
  {
    tokenId: 168n,
    name: "Pallasum Ink",
    description: "Luminescent ink for invisible messages. Only visible under specific magical wavelengths.",
    copperPrice: 160,
    category: "material",
  },
  {
    tokenId: 169n,
    name: "Indinide Clay",
    description: "Moldable clay whose creations can be animated through magical commands.",
    copperPrice: 200,
    category: "material",
  },
  {
    tokenId: 170n,
    name: "Telluron Fiber",
    description: "Strong fiber that conducts magical energy. Used in enchanted garments.",
    copperPrice: 220,
    category: "material",
  },
  {
    tokenId: 171n,
    name: "Iodaron Resin",
    description: "Adhesive resin that permanently bonds any two surfaces together.",
    copperPrice: 140,
    category: "material",
  },
  {
    tokenId: 172n,
    name: "Caesaric Crystal",
    description: "Luminescent crystal that stores and projects holographic images.",
    copperPrice: 280,
    category: "material",
  },
  {
    tokenId: 173n,
    name: "Barylian Wax",
    description: "Heat-resistant wax. Protects enchanted items from extreme temperatures and corrosion.",
    copperPrice: 100,
    category: "material",
  },
  {
    tokenId: 174n,
    name: "Lantharum Pigment",
    description: "Vibrant pigment for enchanted symbols that activate on touch or voice.",
    copperPrice: 170,
    category: "material",
  },
  {
    tokenId: 175n,
    name: "Ceric Foam",
    description: "Temperature-regulating foam for storing sensitive enchanted materials.",
    copperPrice: 130,
    category: "material",
  },
  {
    tokenId: 176n,
    name: "Prasic Glass",
    description: "Flexible, transparent glass for enchanted lenses and containers.",
    copperPrice: 190,
    category: "material",
  },
  {
    tokenId: 177n,
    name: "Neodynic Ink",
    description: "Magnetic ink for messages readable only under a specific magnetic field.",
    copperPrice: 210,
    category: "material",
  },
  {
    tokenId: 178n,
    name: "Promic Crystal",
    description: "Self-healing crystal with regenerative properties. Tools made from it repair themselves.",
    copperPrice: 500,
    category: "material",
  },
  {
    tokenId: 179n,
    name: "Samaronic Silk",
    description: "Iridescent silk that changes color based on ambient lighting. Perfect camouflage material.",
    copperPrice: 240,
    category: "material",
  },
];

export function getItemByTokenId(tokenId: bigint): ItemDefinition | undefined {
  return ITEM_CATALOG.find((item) => item.tokenId === tokenId);
}

/** Return catalog entries filtered to a set of tokenIds. */
export function getItemsByTokenIds(tokenIds: number[]): ItemDefinition[] {
  const set = new Set(tokenIds.map((id) => BigInt(id)));
  return ITEM_CATALOG.filter((item) => set.has(item.tokenId));
}
