import type { CharacterStats } from "./classes.js";

export type ArmorSlot =
  | "chest"
  | "legs"
  | "boots"
  | "helm"
  | "shoulders"
  | "gloves"
  | "belt";
export type WeaponSlot = "weapon";
export type EquipmentSlot = ArmorSlot | WeaponSlot;

export interface ItemStatBonuses extends Partial<CharacterStats> {}

export interface ItemDefinition {
  tokenId: bigint;
  name: string;
  description: string;
  goldPrice: number;
  category: "consumable" | "weapon" | "armor" | "material" | "tool";
  equipSlot?: EquipmentSlot;
  armorSlot?: ArmorSlot;
  statBonuses?: ItemStatBonuses;
  maxDurability?: number;
}

export const ITEM_CATALOG: ItemDefinition[] = [
  // --- Consumables ---
  {
    tokenId: 0n,
    name: "Health Potion",
    description: "Restores 50 HP instantly.",
    goldPrice: 10,
    category: "consumable",
  },
  {
    tokenId: 1n,
    name: "Raw Meat",
    description: "Uncooked meat from slain beasts. Can be cooked for better nutrition.",
    goldPrice: 3,
    category: "material",
  },
  // --- Weapons ---
  {
    tokenId: 2n,
    name: "Iron Sword",
    description: "A sturdy blade forged from iron. +8 ATK.",
    goldPrice: 100,
    category: "weapon",
    equipSlot: "weapon",
    statBonuses: { str: 8 },
    maxDurability: 60,
  },
  {
    tokenId: 3n,
    name: "Steel Longsword",
    description: "A well-balanced longsword of tempered steel. +14 ATK.",
    goldPrice: 250,
    category: "weapon",
    equipSlot: "weapon",
    statBonuses: { str: 14 },
    maxDurability: 80,
  },
  {
    tokenId: 4n,
    name: "Hunter's Bow",
    description: "A lightweight bow favored by meadow hunters. +10 ATK.",
    goldPrice: 150,
    category: "weapon",
    equipSlot: "weapon",
    statBonuses: { str: 4, agi: 6 },
    maxDurability: 70,
  },
  {
    tokenId: 5n,
    name: "Battle Axe",
    description: "A heavy axe that cleaves through armor. +18 ATK.",
    goldPrice: 400,
    category: "weapon",
    equipSlot: "weapon",
    statBonuses: { str: 18, agi: -1 },
    maxDurability: 95,
  },
  {
    tokenId: 6n,
    name: "Apprentice Staff",
    description: "A gnarled staff crackling with faint energy. +12 MAG.",
    goldPrice: 200,
    category: "weapon",
    equipSlot: "weapon",
    statBonuses: { int: 12, faith: 3 },
    maxDurability: 65,
  },
  // --- Armor ---
  {
    tokenId: 7n,
    name: "Oak Shield",
    description: "A solid shield carved from oak wood. +6 DEF.",
    goldPrice: 80,
    category: "armor",
    equipSlot: "weapon",
    statBonuses: { def: 6 },
    maxDurability: 85,
  },
  {
    tokenId: 8n,
    name: "Leather Vest",
    description: "Light armor stitched from tanned hides. +4 DEF.",
    goldPrice: 60,
    category: "armor",
    equipSlot: "chest",
    armorSlot: "chest",
    statBonuses: { def: 4, hp: 4 },
    maxDurability: 70,
  },
  {
    tokenId: 9n,
    name: "Chainmail Shirt",
    description: "Interlocking iron rings provide solid protection. +10 DEF.",
    goldPrice: 300,
    category: "armor",
    equipSlot: "chest",
    armorSlot: "chest",
    statBonuses: { def: 10, hp: 12 },
    maxDurability: 100,
  },
  {
    tokenId: 10n,
    name: "Iron Helm",
    description: "A simple helm that guards against headshots. +3 DEF.",
    goldPrice: 45,
    category: "armor",
    equipSlot: "helm",
    armorSlot: "helm",
    statBonuses: { def: 3, hp: 3 },
    maxDurability: 55,
  },
  {
    tokenId: 12n,
    name: "Leather Leggings",
    description: "Flexible leggings. +2 DEF, +1 AGI.",
    goldPrice: 55,
    category: "armor",
    equipSlot: "legs",
    armorSlot: "legs",
    statBonuses: { def: 2, agi: 1 },
    maxDurability: 60,
  },
  {
    tokenId: 13n,
    name: "Traveler Boots",
    description: "Sturdy boots for long marches. +1 DEF, +2 AGI.",
    goldPrice: 50,
    category: "armor",
    equipSlot: "boots",
    armorSlot: "boots",
    statBonuses: { def: 1, agi: 2 },
    maxDurability: 58,
  },
  {
    tokenId: 14n,
    name: "Bronze Shoulders",
    description: "Simple shoulder guards. +3 DEF.",
    goldPrice: 70,
    category: "armor",
    equipSlot: "shoulders",
    armorSlot: "shoulders",
    statBonuses: { def: 3 },
    maxDurability: 75,
  },
  {
    tokenId: 15n,
    name: "Padded Gloves",
    description: "Reinforced gloves. +1 STR, +1 DEF.",
    goldPrice: 40,
    category: "armor",
    equipSlot: "gloves",
    armorSlot: "gloves",
    statBonuses: { str: 1, def: 1 },
    maxDurability: 50,
  },
  {
    tokenId: 16n,
    name: "Guard Belt",
    description: "A belt that stabilizes your stance. +2 DEF, +4 HP.",
    goldPrice: 60,
    category: "armor",
    equipSlot: "belt",
    armorSlot: "belt",
    statBonuses: { def: 2, hp: 4 },
    maxDurability: 65,
  },
  {
    tokenId: 17n,
    name: "Iron Greaves",
    description: "Heavy greaves for frontline fighters. +5 DEF.",
    goldPrice: 130,
    category: "armor",
    equipSlot: "legs",
    armorSlot: "legs",
    statBonuses: { def: 5, hp: 6 },
    maxDurability: 90,
  },
  {
    tokenId: 18n,
    name: "Steel Sabatons",
    description: "Armored boots. +3 DEF, +1 AGI.",
    goldPrice: 110,
    category: "armor",
    equipSlot: "boots",
    armorSlot: "boots",
    statBonuses: { def: 3, agi: 1 },
    maxDurability: 85,
  },
  {
    tokenId: 19n,
    name: "Knight Gauntlets",
    description: "Heavy gauntlets. +2 STR, +3 DEF.",
    goldPrice: 150,
    category: "armor",
    equipSlot: "gloves",
    armorSlot: "gloves",
    statBonuses: { str: 2, def: 3 },
    maxDurability: 88,
  },
  {
    tokenId: 20n,
    name: "War Belt",
    description: "Battle-forged belt. +4 DEF, +8 HP.",
    goldPrice: 140,
    category: "armor",
    equipSlot: "belt",
    armorSlot: "belt",
    statBonuses: { def: 4, hp: 8 },
    maxDurability: 92,
  },
  {
    tokenId: 21n,
    name: "Steel Pauldrons",
    description: "Reinforced pauldrons. +5 DEF.",
    goldPrice: 165,
    category: "armor",
    equipSlot: "shoulders",
    armorSlot: "shoulders",
    statBonuses: { def: 5, hp: 4 },
    maxDurability: 95,
  },
  // --- Materials ---
  {
    tokenId: 11n,
    name: "Wolf Pelt",
    description: "A pelt harvested from a slain wolf.",
    goldPrice: 5,
    category: "material",
  },
  // --- Ores (Materials) ---
  {
    tokenId: 22n,
    name: "Coal Ore",
    description: "Common black ore used for basic smelting.",
    goldPrice: 8,
    category: "material",
  },
  {
    tokenId: 23n,
    name: "Tin Ore",
    description: "Lightweight ore with a silvery sheen.",
    goldPrice: 12,
    category: "material",
  },
  {
    tokenId: 24n,
    name: "Copper Ore",
    description: "Reddish-brown ore prized by blacksmiths.",
    goldPrice: 20,
    category: "material",
  },
  {
    tokenId: 25n,
    name: "Silver Ore",
    description: "Rare ore that gleams in the light.",
    goldPrice: 45,
    category: "material",
  },
  {
    tokenId: 26n,
    name: "Gold Ore",
    description: "Extremely rare precious ore.",
    goldPrice: 100,
    category: "material",
  },
  // --- Pickaxes (Tools) ---
  {
    tokenId: 27n,
    name: "Stone Pickaxe",
    description: "Crude pickaxe for mining common ores. Tier 1.",
    goldPrice: 30,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 40,
  },
  {
    tokenId: 28n,
    name: "Iron Pickaxe",
    description: "Sturdy pickaxe for harder ores. Tier 2.",
    goldPrice: 80,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 60,
  },
  {
    tokenId: 29n,
    name: "Steel Pickaxe",
    description: "Refined pickaxe for rare ores. Tier 3.",
    goldPrice: 200,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 80,
  },
  {
    tokenId: 30n,
    name: "Mithril Pickaxe",
    description: "Legendary pickaxe that mines gold veins. Tier 4.",
    goldPrice: 500,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 100,
  },
  // --- Flowers (Materials) ---
  {
    tokenId: 31n,
    name: "Meadow Lily",
    description: "Delicate white flowers found in sunny meadows.",
    goldPrice: 5,
    category: "material",
  },
  {
    tokenId: 32n,
    name: "Wild Rose",
    description: "Fragrant pink roses with thorny stems.",
    goldPrice: 6,
    category: "material",
  },
  {
    tokenId: 33n,
    name: "Dandelion",
    description: "Common yellow flower with medicinal properties.",
    goldPrice: 3,
    category: "material",
  },
  {
    tokenId: 34n,
    name: "Clover",
    description: "Lucky four-leaf clover, rare and valuable.",
    goldPrice: 4,
    category: "material",
  },
  {
    tokenId: 35n,
    name: "Lavender",
    description: "Purple aromatic herb with calming properties.",
    goldPrice: 15,
    category: "material",
  },
  {
    tokenId: 36n,
    name: "Sage",
    description: "Silvery-green herb used in magical rituals.",
    goldPrice: 18,
    category: "material",
  },
  {
    tokenId: 37n,
    name: "Mint",
    description: "Refreshing herb with a cool, crisp scent.",
    goldPrice: 12,
    category: "material",
  },
  {
    tokenId: 38n,
    name: "Moonflower",
    description: "Rare white bloom that only opens at night.",
    goldPrice: 40,
    category: "material",
  },
  {
    tokenId: 39n,
    name: "Starbloom",
    description: "Ethereal flower that glows with starlight.",
    goldPrice: 55,
    category: "material",
  },
  {
    tokenId: 40n,
    name: "Dragon's Breath",
    description: "Legendary crimson flower imbued with draconic energy.",
    goldPrice: 120,
    category: "material",
  },
  // --- Sickles (Herbalism Tools) ---
  {
    tokenId: 41n,
    name: "Basic Sickle",
    description: "Simple curved blade for gathering common herbs. Tier 1.",
    goldPrice: 25,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 35,
  },
  {
    tokenId: 42n,
    name: "Iron Sickle",
    description: "Sturdy iron blade for cutting tougher plants. Tier 2.",
    goldPrice: 70,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 55,
  },
  {
    tokenId: 43n,
    name: "Steel Sickle",
    description: "Razor-sharp steel blade for rare flowers. Tier 3.",
    goldPrice: 180,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 75,
  },
  {
    tokenId: 44n,
    name: "Enchanted Sickle",
    description: "Magical sickle that harvests legendary blooms. Tier 4.",
    goldPrice: 450,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 95,
  },
  // --- Potions (Alchemy Products) ---
  {
    tokenId: 45n,
    name: "Minor Health Potion",
    description: "Restores 30 HP. Brewed from meadow lilies and dandelion.",
    goldPrice: 15,
    category: "consumable",
  },
  {
    tokenId: 46n,
    name: "Minor Mana Potion",
    description: "Restores 20 MP. Brewed from wild roses and clover.",
    goldPrice: 18,
    category: "consumable",
  },
  {
    tokenId: 47n,
    name: "Stamina Elixir",
    description: "Increases stamina regeneration for 5 minutes.",
    goldPrice: 30,
    category: "consumable",
  },
  {
    tokenId: 48n,
    name: "Wisdom Potion",
    description: "Grants +10 INT for 10 minutes. Infused with sage and moonflower.",
    goldPrice: 50,
    category: "consumable",
  },
  {
    tokenId: 49n,
    name: "Swift Step Potion",
    description: "Increases movement speed by 20% for 5 minutes.",
    goldPrice: 25,
    category: "consumable",
  },
  {
    tokenId: 50n,
    name: "Greater Health Potion",
    description: "Restores 100 HP. Potent healing brew.",
    goldPrice: 80,
    category: "consumable",
  },
  {
    tokenId: 51n,
    name: "Greater Mana Potion",
    description: "Restores 70 MP. Distilled from starbloom essence.",
    goldPrice: 95,
    category: "consumable",
  },
  {
    tokenId: 52n,
    name: "Elixir of Strength",
    description: "Grants +15 STR for 15 minutes. Dragon's breath infusion.",
    goldPrice: 150,
    category: "consumable",
  },
  {
    tokenId: 53n,
    name: "Elixir of Vitality",
    description: "Grants +20 HP and +10 DEF for 15 minutes.",
    goldPrice: 180,
    category: "consumable",
  },
  {
    tokenId: 54n,
    name: "Philosopher's Elixir",
    description: "Legendary brew that grants +20 to all stats for 30 minutes.",
    goldPrice: 400,
    category: "consumable",
  },
  // --- Enchantment Elixirs (Alchemy Products) ---
  {
    tokenId: 55n,
    name: "Fire Enchantment Elixir",
    description: "Imbues weapons with eternal flames. +5 STR, +10% fire damage.",
    goldPrice: 150,
    category: "consumable",
  },
  {
    tokenId: 56n,
    name: "Ice Enchantment Elixir",
    description: "Sheathes weapons in frost. +3 STR, +2 AGI, 20% slow chance.",
    goldPrice: 140,
    category: "consumable",
  },
  {
    tokenId: 57n,
    name: "Lightning Enchantment Elixir",
    description: "Electrifies weapons. +4 STR, +3 AGI, 30% chain lightning.",
    goldPrice: 160,
    category: "consumable",
  },
  {
    tokenId: 58n,
    name: "Holy Enchantment Elixir",
    description: "Blesses weapons with divine light. +4 STR, +2 DEF, heals 5 HP on hit.",
    goldPrice: 180,
    category: "consumable",
  },
  {
    tokenId: 59n,
    name: "Shadow Enchantment Elixir",
    description: "Cloaks weapons in darkness. +6 STR, +1 AGI, +15% crit chance.",
    goldPrice: 170,
    category: "consumable",
  },
  {
    tokenId: 60n,
    name: "Sharpness Elixir",
    description: "Hones weapons to impossible keenness. +8 STR, +20% vs armor.",
    goldPrice: 200,
    category: "consumable",
  },
  {
    tokenId: 61n,
    name: "Durability Elixir",
    description: "Makes equipment nearly unbreakable. +3 DEF, -50% durability loss.",
    goldPrice: 190,
    category: "consumable",
  },

  // --- Skinning Materials ---
  {
    tokenId: 62n,
    name: "Scrap Leather",
    description: "Rough, low-quality leather from common creatures.",
    goldPrice: 3,
    category: "material",
  },
  {
    tokenId: 63n,
    name: "Light Leather",
    description: "Soft, pliable leather suitable for basic armor.",
    goldPrice: 6,
    category: "material",
  },
  {
    tokenId: 64n,
    name: "Medium Leather",
    description: "Sturdy leather from mid-tier beasts.",
    goldPrice: 12,
    category: "material",
  },
  {
    tokenId: 65n,
    name: "Wolf Pelt",
    description: "Thick fur pelt from a slain wolf.",
    goldPrice: 10,
    category: "material",
  },
  {
    tokenId: 66n,
    name: "Bear Hide",
    description: "Extremely durable hide from a forest bear.",
    goldPrice: 25,
    category: "material",
  },
  {
    tokenId: 67n,
    name: "Spider Silk",
    description: "Fine, enchanted silk harvested from giant spiders.",
    goldPrice: 18,
    category: "material",
  },
  {
    tokenId: 68n,
    name: "Small Bone",
    description: "Common bone fragments from small creatures.",
    goldPrice: 2,
    category: "material",
  },
  {
    tokenId: 69n,
    name: "Thick Bone",
    description: "Large bones from powerful beasts.",
    goldPrice: 8,
    category: "material",
  },
  {
    tokenId: 70n,
    name: "Heavy Leather",
    description: "Premium leather from dangerous creatures.",
    goldPrice: 30,
    category: "material",
  },
  {
    tokenId: 71n,
    name: "Shadow Pelt",
    description: "Mystical fur that shimmers with dark energy.",
    goldPrice: 60,
    category: "material",
  },
  {
    tokenId: 72n,
    name: "Ancient Bone",
    description: "Enchanted bones from undead or ancient beings.",
    goldPrice: 35,
    category: "material",
  },
  {
    tokenId: 73n,
    name: "Troll Hide",
    description: "Regenerative hide from a forest troll.",
    goldPrice: 75,
    category: "material",
  },
  {
    tokenId: 74n,
    name: "Golem Core",
    description: "Magical core extracted from an ancient golem.",
    goldPrice: 100,
    category: "material",
  },
  {
    tokenId: 75n,
    name: "Necromancer's Essence",
    description: "Rare essence of dark magic from a powerful necromancer.",
    goldPrice: 200,
    category: "material",
  },

  // --- Skinning Knives (Tools) ---
  {
    tokenId: 76n,
    name: "Rusty Skinning Knife",
    description: "Crude blade for harvesting basic leather. Tier 1.",
    goldPrice: 25,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 50,
  },
  {
    tokenId: 77n,
    name: "Iron Skinning Knife",
    description: "Sharp knife for skinning mid-tier creatures. Tier 2.",
    goldPrice: 70,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 70,
  },
  {
    tokenId: 78n,
    name: "Steel Skinning Knife",
    description: "Professional skinner's blade for rare hides. Tier 3.",
    goldPrice: 180,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 90,
  },
  {
    tokenId: 79n,
    name: "Master Skinner's Blade",
    description: "Legendary blade that harvests the finest materials. Tier 4.",
    goldPrice: 450,
    category: "tool",
    equipSlot: "weapon",
    maxDurability: 120,
  },

  // --- Mana Potion (moved from tokenId 1) ---
  {
    tokenId: 80n,
    name: "Mana Potion",
    description: "Restores 30 essence instantly.",
    goldPrice: 15,
    category: "consumable",
  },

  // --- Cooked Food (Cooking Profession) ---
  {
    tokenId: 81n,
    name: "Cooked Meat",
    description: "Grilled meat that restores 30 HP.",
    goldPrice: 8,
    category: "consumable",
  },
  {
    tokenId: 82n,
    name: "Hearty Stew",
    description: "A filling stew that restores 60 HP.",
    goldPrice: 18,
    category: "consumable",
  },
  {
    tokenId: 83n,
    name: "Roasted Boar",
    description: "Succulent roasted boar that restores 100 HP.",
    goldPrice: 35,
    category: "consumable",
  },
  {
    tokenId: 84n,
    name: "Bear Feast",
    description: "A luxurious feast that restores 150 HP.",
    goldPrice: 60,
    category: "consumable",
  },
  {
    tokenId: 85n,
    name: "Hero's Banquet",
    description: "An epic meal that restores 250 HP and grants +5 STR for 5 minutes.",
    goldPrice: 120,
    category: "consumable",
  },
];

export function getItemByTokenId(tokenId: bigint): ItemDefinition | undefined {
  return ITEM_CATALOG.find((item) => item.tokenId === tokenId);
}

/** Return catalog entries filtered to a set of tokenIds. */
export function getItemsByTokenIds(tokenIds: number[]): ItemDefinition[] {
  const set = new Set(tokenIds.map((id) => BigInt(id)));
  return ITEM_CATALOG.filter((item) => set.has(item.tokenId));
}
