export type TechniqueType = "attack" | "buff" | "debuff" | "healing";
export type TargetType = "self" | "enemy" | "ally" | "area";

export interface TechniqueEffect {
  damageMultiplier?: number; // For attacks
  healAmount?: number; // For healing (% of max HP)
  statBonus?: Partial<Record<string, number>>; // For buffs (% increase)
  statReduction?: Partial<Record<string, number>>; // For debuffs (% decrease)
  duration?: number; // Duration in seconds for buffs/debuffs/DoTs
  dotDamage?: number; // Damage over time per tick
  shield?: number; // Shield/absorb amount (% of max HP)
  areaRadius?: number; // For area attacks
  maxTargets?: number; // For multi-target attacks
}

export interface TechniqueDefinition {
  id: string;
  name: string;
  description: string;
  className: string;
  levelRequired: number;
  goldCost: number; // Gold to learn from trainer
  essenceCost: number;
  cooldown: number; // seconds
  type: TechniqueType;
  targetType: TargetType;
  effects: TechniqueEffect;
}

export const TECHNIQUES: TechniqueDefinition[] = [
  // WARRIOR
  {
    id: "warrior_heroic_strike",
    name: "Heroic Strike",
    description: "Powerful melee strike dealing 150% weapon damage",
    className: "warrior",
    levelRequired: 1,
    goldCost: 10,
    essenceCost: 15,
    cooldown: 6,
    type: "attack",
    targetType: "enemy",
    effects: { damageMultiplier: 1.5 },
  },
  {
    id: "warrior_shield_wall",
    name: "Shield Wall",
    description: "Increases defense by 50% for 10 seconds",
    className: "warrior",
    levelRequired: 3,
    goldCost: 30,
    essenceCost: 20,
    cooldown: 30,
    type: "buff",
    targetType: "self",
    effects: { statBonus: { def: 50 }, duration: 10 },
  },
  {
    id: "warrior_intimidating_shout",
    name: "Intimidating Shout",
    description: "Reduces enemy attack power by 30% for 8 seconds",
    className: "warrior",
    levelRequired: 6,
    goldCost: 60,
    essenceCost: 25,
    cooldown: 20,
    type: "debuff",
    targetType: "enemy",
    effects: { statReduction: { str: 30 }, duration: 8 },
  },
  {
    id: "warrior_battle_rage",
    name: "Battle Rage",
    description: "Increases strength by 40% for 12 seconds",
    className: "warrior",
    levelRequired: 9,
    goldCost: 90,
    essenceCost: 30,
    cooldown: 45,
    type: "buff",
    targetType: "self",
    effects: { statBonus: { str: 40 }, duration: 12 },
  },
  {
    id: "warrior_cleave",
    name: "Cleave",
    description: "Sweeping attack hitting up to 3 nearby enemies",
    className: "warrior",
    levelRequired: 12,
    goldCost: 120,
    essenceCost: 35,
    cooldown: 10,
    type: "attack",
    targetType: "area",
    effects: { damageMultiplier: 1.2, maxTargets: 3 },
  },

  // PALADIN
  {
    id: "paladin_holy_smite",
    name: "Holy Smite",
    description: "Melee strike dealing weapon + holy damage",
    className: "paladin",
    levelRequired: 1,
    goldCost: 10,
    essenceCost: 18,
    cooldown: 5,
    type: "attack",
    targetType: "enemy",
    effects: { damageMultiplier: 1.3 },
  },
  {
    id: "paladin_divine_shield",
    name: "Divine Shield",
    description: "Grants 80% damage reduction for 6 seconds",
    className: "paladin",
    levelRequired: 3,
    goldCost: 30,
    essenceCost: 40,
    cooldown: 60,
    type: "buff",
    targetType: "self",
    effects: { statBonus: { def: 80 }, duration: 6 },
  },
  {
    id: "paladin_lay_on_hands",
    name: "Lay on Hands",
    description: "Self-heal restoring 50% max HP",
    className: "paladin",
    levelRequired: 6,
    goldCost: 60,
    essenceCost: 50,
    cooldown: 120,
    type: "healing",
    targetType: "self",
    effects: { healAmount: 50 },
  },
  {
    id: "paladin_consecration",
    name: "Consecration",
    description: "Holy ground deals damage over time to enemies standing in it",
    className: "paladin",
    levelRequired: 9,
    goldCost: 90,
    essenceCost: 35,
    cooldown: 25,
    type: "debuff",
    targetType: "area",
    effects: { dotDamage: 10, duration: 8, areaRadius: 5 },
  },
  {
    id: "paladin_blessing_of_might",
    name: "Blessing of Might",
    description: "Increases strength by 25% for 15 seconds",
    className: "paladin",
    levelRequired: 12,
    goldCost: 120,
    essenceCost: 25,
    cooldown: 30,
    type: "buff",
    targetType: "self",
    effects: { statBonus: { str: 25 }, duration: 15 },
  },

  // ROGUE
  {
    id: "rogue_backstab",
    name: "Backstab",
    description: "High damage strike, 200% damage from behind",
    className: "rogue",
    levelRequired: 1,
    goldCost: 10,
    essenceCost: 20,
    cooldown: 8,
    type: "attack",
    targetType: "enemy",
    effects: { damageMultiplier: 2.0 },
  },
  {
    id: "rogue_stealth",
    name: "Stealth",
    description: "Become invisible, lasts until first attack",
    className: "rogue",
    levelRequired: 3,
    goldCost: 30,
    essenceCost: 30,
    cooldown: 40,
    type: "buff",
    targetType: "self",
    effects: { duration: 30 }, // Special stealth mechanic
  },
  {
    id: "rogue_poison_blade",
    name: "Poison Blade",
    description: "Apply poison dealing damage over 12 seconds",
    className: "rogue",
    levelRequired: 6,
    goldCost: 60,
    essenceCost: 25,
    cooldown: 15,
    type: "debuff",
    targetType: "enemy",
    effects: { dotDamage: 15, duration: 12 },
  },
  {
    id: "rogue_evasion",
    name: "Evasion",
    description: "Increase dodge chance by 60% for 8 seconds",
    className: "rogue",
    levelRequired: 9,
    goldCost: 90,
    essenceCost: 35,
    cooldown: 50,
    type: "buff",
    targetType: "self",
    effects: { statBonus: { agi: 60 }, duration: 8 },
  },
  {
    id: "rogue_shadow_strike",
    name: "Shadow Strike",
    description: "Teleport behind target and strike for 180% damage",
    className: "rogue",
    levelRequired: 12,
    goldCost: 120,
    essenceCost: 40,
    cooldown: 20,
    type: "attack",
    targetType: "enemy",
    effects: { damageMultiplier: 1.8 },
  },

  // RANGER
  {
    id: "ranger_aimed_shot",
    name: "Aimed Shot",
    description: "Precise ranged attack dealing 160% damage",
    className: "ranger",
    levelRequired: 1,
    goldCost: 10,
    essenceCost: 15,
    cooldown: 6,
    type: "attack",
    targetType: "enemy",
    effects: { damageMultiplier: 1.6 },
  },
  {
    id: "ranger_hunters_mark",
    name: "Hunter's Mark",
    description: "Mark target to take 25% more damage for 15 seconds",
    className: "ranger",
    levelRequired: 3,
    goldCost: 30,
    essenceCost: 20,
    cooldown: 25,
    type: "debuff",
    targetType: "enemy",
    effects: { statReduction: { def: 25 }, duration: 15 },
  },
  {
    id: "ranger_quick_shot",
    name: "Quick Shot",
    description: "Rapid fire dealing 80% damage, instant cast",
    className: "ranger",
    levelRequired: 6,
    goldCost: 60,
    essenceCost: 10,
    cooldown: 3,
    type: "attack",
    targetType: "enemy",
    effects: { damageMultiplier: 0.8 },
  },
  {
    id: "ranger_natures_blessing",
    name: "Nature's Blessing",
    description: "Heal 30% HP over 10 seconds",
    className: "ranger",
    levelRequired: 9,
    goldCost: 90,
    essenceCost: 30,
    cooldown: 40,
    type: "healing",
    targetType: "self",
    effects: { healAmount: 30, duration: 10 },
  },
  {
    id: "ranger_multi_shot",
    name: "Multi-Shot",
    description: "Fire arrows at up to 4 targets for 100% damage each",
    className: "ranger",
    levelRequired: 12,
    goldCost: 120,
    essenceCost: 40,
    cooldown: 15,
    type: "attack",
    targetType: "area",
    effects: { damageMultiplier: 1.0, maxTargets: 4 },
  },

  // MAGE
  {
    id: "mage_fireball",
    name: "Fireball",
    description: "Ranged fire damage projectile",
    className: "mage",
    levelRequired: 1,
    goldCost: 10,
    essenceCost: 20,
    cooldown: 4,
    type: "attack",
    targetType: "enemy",
    effects: { damageMultiplier: 1.4 },
  },
  {
    id: "mage_frost_armor",
    name: "Frost Armor",
    description: "Increases defense by 30%, slows attackers",
    className: "mage",
    levelRequired: 3,
    goldCost: 30,
    essenceCost: 25,
    cooldown: 30,
    type: "buff",
    targetType: "self",
    effects: { statBonus: { def: 30 }, duration: 20 },
  },
  {
    id: "mage_arcane_missiles",
    name: "Arcane Missiles",
    description: "5 magic projectiles, each dealing damage",
    className: "mage",
    levelRequired: 6,
    goldCost: 60,
    essenceCost: 35,
    cooldown: 10,
    type: "attack",
    targetType: "enemy",
    effects: { damageMultiplier: 1.8 }, // Total 1.8x damage split across 5 missiles
  },
  {
    id: "mage_slow",
    name: "Slow",
    description: "Reduces enemy agility by 50% for 10 seconds",
    className: "mage",
    levelRequired: 9,
    goldCost: 90,
    essenceCost: 30,
    cooldown: 20,
    type: "debuff",
    targetType: "enemy",
    effects: { statReduction: { agi: 50 }, duration: 10 },
  },
  {
    id: "mage_flamestrike",
    name: "Flamestrike",
    description: "Area spell hitting all enemies in radius",
    className: "mage",
    levelRequired: 12,
    goldCost: 120,
    essenceCost: 50,
    cooldown: 25,
    type: "attack",
    targetType: "area",
    effects: { damageMultiplier: 1.5, areaRadius: 8 },
  },

  // CLERIC
  {
    id: "cleric_holy_light",
    name: "Holy Light",
    description: "Heal target for 40% max HP",
    className: "cleric",
    levelRequired: 1,
    goldCost: 10,
    essenceCost: 25,
    cooldown: 5,
    type: "healing",
    targetType: "self",
    effects: { healAmount: 40 },
  },
  {
    id: "cleric_divine_protection",
    name: "Divine Protection",
    description: "Shield absorbing 35% max HP damage",
    className: "cleric",
    levelRequired: 3,
    goldCost: 30,
    essenceCost: 30,
    cooldown: 25,
    type: "buff",
    targetType: "self",
    effects: { shield: 35, duration: 15 },
  },
  {
    id: "cleric_smite",
    name: "Smite",
    description: "Holy damage, extra effective vs undead",
    className: "cleric",
    levelRequired: 6,
    goldCost: 60,
    essenceCost: 20,
    cooldown: 6,
    type: "attack",
    targetType: "enemy",
    effects: { damageMultiplier: 1.3 },
  },
  {
    id: "cleric_renew",
    name: "Renew",
    description: "Heal 45% HP over 12 seconds",
    className: "cleric",
    levelRequired: 9,
    goldCost: 90,
    essenceCost: 35,
    cooldown: 15,
    type: "healing",
    targetType: "self",
    effects: { healAmount: 45, duration: 12 },
  },
  {
    id: "cleric_prayer_of_fortitude",
    name: "Prayer of Fortitude",
    description: "Increases max HP by 20% for 20 seconds",
    className: "cleric",
    levelRequired: 12,
    goldCost: 120,
    essenceCost: 40,
    cooldown: 60,
    type: "buff",
    targetType: "self",
    effects: { statBonus: { hp: 20 }, duration: 20 },
  },

  // WARLOCK
  {
    id: "warlock_shadow_bolt",
    name: "Shadow Bolt",
    description: "Dark magic projectile",
    className: "warlock",
    levelRequired: 1,
    goldCost: 10,
    essenceCost: 18,
    cooldown: 4,
    type: "attack",
    targetType: "enemy",
    effects: { damageMultiplier: 1.35 },
  },
  {
    id: "warlock_curse_of_weakness",
    name: "Curse of Weakness",
    description: "Reduces enemy strength by 35% for 12 seconds",
    className: "warlock",
    levelRequired: 3,
    goldCost: 30,
    essenceCost: 25,
    cooldown: 18,
    type: "debuff",
    targetType: "enemy",
    effects: { statReduction: { str: 35 }, duration: 12 },
  },
  {
    id: "warlock_drain_life",
    name: "Drain Life",
    description: "Deal damage and heal self for 50% of damage dealt",
    className: "warlock",
    levelRequired: 6,
    goldCost: 60,
    essenceCost: 30,
    cooldown: 12,
    type: "attack",
    targetType: "enemy",
    effects: { damageMultiplier: 1.2, healAmount: 50 }, // Special lifesteal
  },
  {
    id: "warlock_soul_shield",
    name: "Soul Shield",
    description: "Absorb 40% max HP damage using essence",
    className: "warlock",
    levelRequired: 9,
    goldCost: 90,
    essenceCost: 45,
    cooldown: 35,
    type: "buff",
    targetType: "self",
    effects: { shield: 40, duration: 10 },
  },
  {
    id: "warlock_corruption",
    name: "Corruption",
    description: "Strong damage over time curse, lasts 15 seconds",
    className: "warlock",
    levelRequired: 12,
    goldCost: 120,
    essenceCost: 35,
    cooldown: 20,
    type: "debuff",
    targetType: "enemy",
    effects: { dotDamage: 20, duration: 15 },
  },

  // MONK
  {
    id: "monk_palm_strike",
    name: "Palm Strike",
    description: "Quick unarmed strike dealing 130% damage",
    className: "monk",
    levelRequired: 1,
    goldCost: 10,
    essenceCost: 12,
    cooldown: 4,
    type: "attack",
    targetType: "enemy",
    effects: { damageMultiplier: 1.3 },
  },
  {
    id: "monk_inner_focus",
    name: "Inner Focus",
    description: "Increases critical hit chance by 30% for 10 seconds",
    className: "monk",
    levelRequired: 3,
    goldCost: 30,
    essenceCost: 20,
    cooldown: 30,
    type: "buff",
    targetType: "self",
    effects: { statBonus: { luck: 30 }, duration: 10 },
  },
  {
    id: "monk_disable",
    name: "Disable",
    description: "Reduces enemy agility by 40% for 8 seconds",
    className: "monk",
    levelRequired: 6,
    goldCost: 60,
    essenceCost: 18,
    cooldown: 15,
    type: "debuff",
    targetType: "enemy",
    effects: { statReduction: { agi: 40 }, duration: 8 },
  },
  {
    id: "monk_chi_burst",
    name: "Chi Burst",
    description: "Energy blast dealing 170% damage",
    className: "monk",
    levelRequired: 9,
    goldCost: 90,
    essenceCost: 30,
    cooldown: 10,
    type: "attack",
    targetType: "enemy",
    effects: { damageMultiplier: 1.7 },
  },
  {
    id: "monk_meditation",
    name: "Meditation",
    description: "Channel to heal 60% HP over 6 seconds",
    className: "monk",
    levelRequired: 12,
    goldCost: 120,
    essenceCost: 0, // Free, but channeled
    cooldown: 45,
    type: "healing",
    targetType: "self",
    effects: { healAmount: 60, duration: 6 },
  },
];

export function getTechniqueById(id: string): TechniqueDefinition | undefined {
  return TECHNIQUES.find((t) => t.id === id);
}

export function getTechniquesByClass(className: string): TechniqueDefinition[] {
  return TECHNIQUES.filter((t) => t.className === className);
}

export function getLearnedTechniques(className: string, level: number): TechniqueDefinition[] {
  return TECHNIQUES.filter((t) => t.className === className && t.levelRequired <= level);
}
